spring:
  application:
    name: serviceb

management:
  security:
    enabled: false

server:
  port: 8090

grpc:
  port : 6600

serviceC:
  host: localhost
  grpcPort: 6610
  grpcDeadlineTimeoutInSeconds: 60

zipkin:
  enabled: true
  host: localhost
  port: 9411
  serviceName: service-b