spring:
  application:
    name: serviceb

management:
  security:
    enabled: false

server:
  port: 8090

grpc:
  port : 6600

serviceB:
  host: localhost
  grpcPort:
  grpcDeadlineTimeoutInSeconds: 60

zipkin:
  enabled: true
  host: localhost
  port: 32771
  serviceName: service-b