spring:
  application:
    name: servicec

management:
  security:
    enabled: false

server:
  port: 8100

grpc:
  port: 6610

zipkin:
  enabled: true
  host: localhost
  port: 32769
  serviceName: service-c