spring:
  application:
    name: servicea

management:
  security:
    enabled: false

server:
  port: 8080

serviceB:
  host: localhost
  grpcPort: 6600
  grpcDeadlineTimeoutInSeconds: 60

zipkin:
  enabled: true
  host: localhost
  port: 9411
  serviceName: service-a

hystrix.command.default.execution.isolation.strategy: SEMAPHORE